Filter Services with no perfdata
Icinga/icingaweb2-module-graphite pull request #244
Opened 2020-06-27 16:42 UTC by Virsacer

Hi,
services that don't have perfdata can be removed from the list.

This is my first pull-request ever, so I hope I did it correctly...

2020-09-22 15:50 UTC, Al2Klimov requested changes
Hello @Virsacer and thank you for contributing!

Please provide before/after screenshots once you've addressed my change requests.

Also don't forget to use `git commit --amend`.

Best,
AK

2020-09-22 15:50 UTC, Al2Klimov commented on application/controllers/ListController.php
> +use Icinga\Data\Filter\Filter;
Please keep the uses sorted alphabetically.

2020-09-22 15:50 UTC, Al2Klimov commented on application/controllers/ListController.php
> +
Please do the same for hosts.

2020-09-27 20:32 UTC, Virsacer commented
Before:
![image](https://user-images.githubusercontent.com/8797510/94375037-f9623700-0110-11eb-8374-7291958eb589.png)

After:
![image](https://user-images.githubusercontent.com/8797510/94375041-fcf5be00-0110-11eb-9f86-9906596b46b3.png)

2020-09-28 08:56 UTC, Al2Klimov requested changes
Please also provide hosts screenshots.

2020-09-28 10:54 UTC, Virsacer commented
@Al2Klimov My host-checks all have performance-data so there would be no visible difference.
And if they hadn't then the difference would be the same as in the services screenshot - just with diffenrent names...

2020-09-28 10:55 UTC, Al2Klimov commented
Does the hosts view at least work at all with the currently pushed commit?

2020-09-28 16:28 UTC, Virsacer commented
Ofcourse it does :-)

2020-09-29 07:28 UTC, Al2Klimov approved these changes
Fine.

2020-09-29 07:42 UTC, bobapple approved these changes

2020-09-29 07:45 UTC, merged