Skip missing template metrics
Icinga/icingaweb2-module-graphite pull request #249
Opened 2020-09-30 16:38 UTC by Virsacer

Fix for "Make all macros used in a template's metrics filters available in its functions, too" #217 as requested by @Al2Klimov

2020-09-30 16:41 UTC, Al2Klimov requested changes

2020-09-30 16:41 UTC, Al2Klimov commented on library/Graphite/Web/Widget/GraphImage.php
> +
Please use our code style as in the other ifs.

2020-09-30 16:47 UTC, Al2Klimov approved these changes

2020-10-02 06:45 UTC, bobapple approved these changes

2020-10-02 10:59 UTC, merged