Remove demo Dockerfile
Icinga/icingaweb2-module-graphite pull request #289
Opened 2022-10-20 10:26 UTC by Al2Klimov

2022-10-21 06:45 UTC, lippserd requested changes
Please rename `Demonstration` to `Development`.

2022-10-26 11:33 UTC, lippserd requested changes

2022-10-26 12:51 UTC, Al2Klimov commented on doc/06-Development.md
> +# <a id="Development"></a>Development
Actually these are everywhere, not just there.

Suggestion:

Let’s get done this and #285 and I'll clean them up afterwards.

2022-10-26 12:54 UTC, lippserd commented on doc/06-Development.md
> +# <a id="Development"></a>Development
I am talking about this one only, since you are touching this file. Please just remove it.

2022-10-26 12:55 UTC, Al2Klimov commented on doc/06-Development.md
> +# <a id="Development"></a>Development
Apropos get done: any objections regarding merging #285 before this one?

2022-10-26 12:56 UTC, Al2Klimov commented on doc/06-Development.md
> +# <a id="Development"></a>Development
> I am talking about this one only, since you are touching this file. Please just remove it.

OK

2022-10-26 13:04 UTC, lippserd approved these changes
❤️

2022-10-26 13:04 UTC, merged