Add Graphite Web HTTP request timeout option
Icinga/icingaweb2-module-graphite pull request #321
Opened 2024-02-01 13:11 UTC by atj

If the Graphite Web server is unreachable, all requests for frontend pages containing graphs hang until the backend HTTP request times out, resulting in a very poor UX.

The Guzzle documentation states that the default behaviour is to wait indefinitely, however in our testing the cURL handler has an internal default of 30 seconds:

https://docs.guzzlephp.org/en/stable/request-options.html#timeout

This commit makes the HTTP request timeout configurable and sets a reasonable default of 10 seconds.

2024-02-01 14:21 UTC, nilmerg commented on library/Graphite/Graphing/GraphiteWebClient.php
> +     * @param int $timeout
```suggestion
     * @param ?int $timeout
```

2024-02-01 14:22 UTC, nilmerg commented on library/Graphite/Graphing/GraphiteWebClient.php
> +    public function setTimeout($timeout)
```suggestion
    public function setTimeout(?int $timeout): self
```

2024-02-01 14:22 UTC, nilmerg commented on library/Graphite/Graphing/GraphiteWebClient.php
> +     * @return int
```suggestion
     * @return ?int
```

2024-02-01 14:23 UTC, nilmerg commented on library/Graphite/Graphing/GraphiteWebClient.php
> +    public function getTimeout()
```suggestion
    public function getTimeout(): ?int
```

2024-02-01 15:12 UTC, atj commented
@nilmerg Thanks for the suggestions. I had tried to fix the type safety issues reported by PHPStan but couldn't understand why the following calls weren't triggering the same errors:

https://github.com/Icinga/icingaweb2-module-graphite/blob/254ff35b31ac8c8f26d333e501ead11ec47666a9/library/Graphite/Graphing/GraphingTrait.php#L71-L73

I applied the suggestions locally and PHPStan raised the same error with a slightly different expected type:

```
$ vendor/bin/phpstan analyse library/ application/
Note: Using configuration file icingaweb2-module-graphite/phpstan.neon.
 42/42 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ -------------------------------------------------------------------------------------------------------------------------------- 
  Line   library/Graphite/Graphing/GraphingTrait.php (in context of class Icinga\Module\Graphite\Clicommands\Icinga2Command)             
 ------ -------------------------------------------------------------------------------------------------------------------------------- 
  :74    Parameter #1 $timeout of method Icinga\Module\Graphite\Graphing\GraphiteWebClient::setTimeout() expects int|null, mixed given.  
 ------ -------------------------------------------------------------------------------------------------------------------------------- 
```

2024-02-01 15:22 UTC, nilmerg commented
The problem is that the config section type has no idea of its contained properties and hence phpstan complains rightfully about the unsafe handling. The config might as well contain `timeout = "20"` which is a string.

To fix this, I'd suggest to use this in `GraphingTrait`:

`setTimeout(isset($graphite->timeout) ? (int) $graphite->timeout : null)`

2024-02-14 14:53 UTC, nilmerg commented
Extending the baseline isn't an option.

2024-02-14 17:13 UTC, atj commented
> Extending the baseline isn't an option.

PHPStan is not throwing type errors for the other config fields because they being ignored via entries in the baseline:

https://github.com/Icinga/icingaweb2-module-graphite/blob/254ff35b31ac8c8f26d333e501ead11ec47666a9/phpstan-baseline.neon#L68-L76

As the `Icinga\Data\ConfigObject` accessors are returning `mixed` values, I don't believe it's possible to make the call to `setTimeout` type safe, so it's the only option.

2024-02-15 13:59 UTC, nilmerg requested changes
If you rebase, phpstan shouldn't complain anymore.

We've introduced phpstan to our CI toolstack just recently and didn't adjust most of what it complained about. Hence why the baselines are rather large at the moment. Though, adding additional entries to those isn't helpful in any way as it renders phpstan useless after all.

I've played around with generics just recently and now added them to Icinga Web's `ConfigObject`. This allows us to define here what our config contains. I've did that now in the default branch and you don't have to do anything, other than rebasing. So please drop the changes in the baseline.

2024-02-15 13:59 UTC, nilmerg commented on library/Graphite/Graphing/GraphiteWebClient.php
> +                'timeout' => $this->timeout
I'd like to see this changed still. There's no guarantee guzzle handles `null` fine while it only speaks of supporting floats as timeout.

2024-02-15 17:16 UTC, atj commented
Thanks for your help on this. I've removed the baseline changes and ensured that Guzzle isn't passed a null value for timeout.

2024-02-20 14:41 UTC, nilmerg approved these changes

2024-02-20 14:43 UTC, merged