Update templates for Icinga Powershell plugins
Icinga/icingaweb2-module-graphite pull request #324
Opened 2024-04-05 10:30 UTC by sukhwinder33445

fixes #322

2024-04-09 08:27 UTC, sukhwinder33445 commented
Used prefdata for tests:
```
'a1::b1::c1'=3894494000B;5797273500;6119344250;0;6441415000
'a2::b2::c2'=0;5797273500;6119344250;0;6441415000
'a3::b3::c3'=3894494000B;;6119344250;0;6441415000
'a4::b4::c4'=3894494000B;5797273500;;0;6441415000
'a5::b5::c5'=3894494000B;5797273500;6119344250;;6441415000
'a6::b6::c6'=3894494000B;5797273500;6119344250;0;
'a0::b0::c0'=0B;0;0;0;0
'a21::b21::c21'=0;;;;
'a22::b22::c22'=0;0;;;
'a23::b23::c23'=0;;0;;
'a24::b24::c24'=0;;;0;
'a25::b25::c25'=0;;;;0
'a26::b26::c26'=0;0;0;0;0
'a27::b27::c27'=;;;;
```

2024-10-23 11:19 UTC, tbauriedel requested changes
The introduced `cpu_windows_powershell_framework.ini` and `disk_windows_powershell_framework.ini` works fine in me environment.
But `memory_windows_powershell_framework.ini` is not working for me.  

It cant find the needed index.
```
Undefined index: icinga2.icinga-windows.services.Invoke-IcingaCheckMemory.Invoke-IcingaCheckMemory.perfdata.cpagefilesys.ifw_pagefile.used.value
```

But the index exists on the machine.
I am not 100% sure if this is a bug inside of the template or a failure inside of the environment.  
I still have the setup. We can have a look together if you want.

2024-10-23 11:52 UTC, sukhwinder33445 commented
Hi @tbauriedel,

Can you please provide the `performance data`. This can be found under `detail view (corresponding object) -> Source tab`.

2024-10-23 11:55 UTC, tbauriedel commented
Sure.

```
[
    "memory::ifw_memory::used=2413936000B;3435528000;3864969000;0;4294410000",
    "cpagefilesys::ifw_pagefile::used=242221100B;;;0;1476395000"
]
```

2025-01-14 08:40 UTC, sukhwinder33445 commented
Hi @tbauriedel, 

Now I've been able to reproduce the problem.

2025-01-14 09:11 UTC, sukhwinder33445 commented
https://github.com/Icinga/icingaweb2-module-graphite/pull/327 is the fix for it, please test if possible, just merge the mentioned branch.

2025-01-14 09:20 UTC, tbauriedel commented
We've just talked about it off the record. The problem if now solved, it should fit.

2025-01-14 09:20 UTC, tbauriedel approved these changes

2025-01-16 08:21 UTC, nilmerg approved these changes

2025-01-16 08:21 UTC, merged